services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shortener
    volumes:
      - postgres_data:/bitnami/postgresql
      - './docker:/docker-entrypoint-initdb.d'
  api:
    build: . 
    ports:
      - '3333:3333'
    env_file:
      - .env 
    depends_on:
      - pg
      
volumes:
  postgres_data: